### ISSUE TITLE
SSH commands with double quotes fail

### ISSUE THREAD

**Issue by luzlab** [StrictlySkyler/ssh#4]
Any SSH commands with doublequotes get truncated at the first doublequote.

I think the `"` character needs to get replaced with `&quote`. It appears there's an npm module [js-htmlencode](https://www.npmjs.com/package/js-htmlencode) that handles this conversion (and probably more...)

**Comment by luzlab** [comment]
I submitted PR #5 to fix this.

**Comment by strictlyskyler** [comment]
Merged.
